#!/bin/sh

java -cp /usr/share/java/commons-httpclient.jar:/usr/share/java/commons-logging.jar:/usr/share/java/commons-codec.jar:/usr/share/java/xml-commons-apis.jar:CloudStack.jar net.datapipe.CloudStack.stopVirtualMachine $*
